services:
  backend:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./:/app/dev
      - ignore:/app/dev/node_modules/
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:password@postgres:5432/raceapp
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: raceapp
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    ports:
      - '3001:3000'
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run dev

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8080:80'

volumes:
  ignore: