services:
  backend:
    build:
      context: ./backend
    ports: 
      - '3000:3000'
    volumes: 
      - ./backend:/docker-app
      - /docker-app/node_modules
    command:
      - nodemon 
      - -L
      - server.js
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:password@postgres:5432/raceapp
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: raceapp
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data